### ISSUE TITLE
need support to operate _id

### ISSUE THREAD

**Issue by nhhockeyplayer** [szokodiakos/typegoose#121]
Interfaces are not possible if we implement

id: string
  or
_id: string

mongoose barks either way

unable to model mongoose virtual functions

having to try and accommodate _id is causing upstream havoc in isomorphic interfaces

mongoose refuses to allow us to model an ID or an _ID in our isomorphic interfaces

it has to be done as a virtual
and I see no support for adding virtuals in typegoose

any help is appreciated

**Comment by nhhockeyplayer** [comment]
tried using _id as a property

    @prop()
    _id?: string;

and keep receiving this error

ERROR in src/server/model/IUserModel.ts(4,11): error TS2320: Interface 'IUserModel' cannot simultaneously extend types 'IUser' and 'Document'.
  Named property '_id' of types 'IUser' and 'Document' are not identical.

**Comment by nhhockeyplayer** [comment]
ok I seem to have gotten this to work

here is my typegoose model def class
```
    @prop()
    id?: mongoose.Types.ObjectId;
```

here is my interface

```
interface IUserModel extends IUser, mongoose.Document {
    id?: Types.ObjectId;
```

using it as a property does just work
type alignment is required
and elimination of the underscore 

using latest mongoose and typegoose

**Comment by nhhockeyplayer** [comment]
I am reopening this because mongoose insists on storing models using _id

and thats whats landing in the mongodb

my exercising of @prop id was a side show it had no affect as it does not sync with the mongoose objectId as denoted by _id

this needs to be resolved with virtual function support in typegoose

**Comment by kyle-mccarthy** [comment]
Would this alleviate the problems that you are having?

```
@pre<T>('save', async function (next) {
  if (this._id === undefined || this._id === null) {
    this._id = Types.ObjectId();
  }
  next();
})

export class T extends Typegoose {
  @prop()
  _id?: Types.ObjectId;

  @instanceMethod
  id() {
    return this._id;
  }
  
  ...
}
```

**Comment by naivefun** [comment]
```typescript
export const DefaultJsonTransformOptions = {
  versionKey: false,
  virtuals: true,
  transform: (doc: any, ret: any) => {
    delete ret._id;
  }
};

export function toJSON(doc: Document, options?: DocumentToObjectOptions) {
  return doc.toJSON(options || DefaultJsonTransformOptions);
}

const data = await ProjectModel.findById('id');
return toJSON(data);
```

with this you should be able to define `id: string` just fine in Interface.

**Comment by vemuez** [comment]
Didn't know this existing till now haha. I've implemented it this way.

```
new MyClass().getModelForClass(MyClass, { 
    schemaOptions: {
        toJSON: {
            virtuals: true,
            versionKey: false,
            transform: (doc, ret, options) => {
                delete ret._id;
                return ret;
            }
        }
    }
})
```
or 

```
const DefaultTransform = {
    schemaOptions: {
        toJSON: {
            virtuals: true,
            versionKey: false,
            transform: (doc, ret, options) => {
                delete ret._id;
                return ret;
            }
        }
    }
}

new MyClass().getModelForClass(MyClass, DefaultTransform)
```

**Comment by sladg** [comment]
Any fix for this? 
I need to be able to check `_id` but Typescript is giving me error as of `_id` does not exist on a model.

**Comment by kettuvitonen** [comment]
> Any fix for this?
> I need to be able to check `_id` but Typescript is giving me error as of `_id` does not exist on a model.

Just define `_id` without `prop` decorator.


```
export class User extends Typegoose {
    _id: Schema.Types.ObjectId;
    createdAt: Date;
    updatedAt: Date;

    @prop({ required: true, unique: true, minlength: 4, maxlength: 32 })
    username: string;
...
}
```

**Comment by Paic** [comment]
> > Any fix for this?
> > I need to be able to check `_id` but Typescript is giving me error as of `_id` does not exist on a model.
> 
> Just define `_id` without `prop` decorator.
> 
> ```
> export class User extends Typegoose {
>     _id: Schema.Types.ObjectId;
>     createdAt: Date;
>     updatedAt: Date;
> 
>     @prop({ required: true, unique: true, minlength: 4, maxlength: 32 })
>     username: string;
> ...
> }
> ```

---

This allow access to `user._id`, but `JSON.stringify(user)` is still missing `_id`. Am I doing something wrong ?

**Comment by hasezoey** [comment]
@Paic is there a value without `_`? (also just `id`)

**Comment by Paic** [comment]
Typescript is complaining because it is not defined in the schema, but `id` is accessible with `user.id`.

`JSON.stringify(user)` is missing both `_id` and `id`. Adding `id: Types.ObjectId` did not do it either.

By enabling virtuals in the toJSON options :
```
const UserModel = new User().getModelForClass(User, { schemaOptions: { toJSON: { virtuals: true } } });
...
JSON.stringify(user)
```

The stringified `user` does have the `id` property (no `_id` of course).

**Comment by hasezoey** [comment]
the original issue is about "virtual properties", which is implemented

-> this can be closed
@Ben305
